//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "awards")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub status: String,
    pub user_created: Option<Uuid>,
    pub date_created: Option<DateTimeWithTimeZone>,
    pub user_updated: Option<Uuid>,
    pub date_updated: Option<DateTimeWithTimeZone>,
    pub award_designation: Option<String>,
    pub award_designation_short: Option<String>,
    pub project: Option<i32>,
    pub project_name: Option<String>,
    pub project_location: Option<String>,
    pub year: Option<i32>,
    pub awards_page_sort: Option<i32>,
    pub project_page_sort: Option<i32>,
    pub name: Option<String>,
    pub slug: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::directus_users::Entity",
        from = "Column::UserCreated",
        to = "super::directus_users::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    DirectusUsers2,
    #[sea_orm(
        belongs_to = "super::directus_users::Entity",
        from = "Column::UserUpdated",
        to = "super::directus_users::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    DirectusUsers1,
    #[sea_orm(
        belongs_to = "super::projects::Entity",
        from = "Column::Project",
        to = "super::projects::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Projects,
}

impl Related<super::projects::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Projects.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
