//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "books")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub status: String,
    pub sort: Option<i32>,
    pub user_created: Option<Uuid>,
    pub date_created: Option<DateTimeWithTimeZone>,
    pub user_updated: Option<Uuid>,
    pub date_updated: Option<DateTimeWithTimeZone>,
    pub seo_page_description: Option<String>,
    pub home_page_tagline: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub home_page_blurb: Option<String>,
    pub banner_image: Option<Uuid>,
    pub banner_image_description: Option<String>,
    pub banner_image_mobile: Option<Uuid>,
    pub banner_image_mobile_description: Option<String>,
    pub hero_image: Option<Uuid>,
    pub hero_image_description: Option<String>,
    pub grid_image: Option<Uuid>,
    pub grid_image_description: Option<String>,
    pub tag: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub book_description: Option<String>,
    pub authors: Option<String>,
    pub format: Option<String>,
    pub page_count: Option<i32>,
    pub weight: Option<i32>,
    pub visual_profile_books_link: Option<String>,
    pub amazon_link: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub body: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::directus_files::Entity",
        from = "Column::BannerImage",
        to = "super::directus_files::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    DirectusFiles4,
    #[sea_orm(
        belongs_to = "super::directus_files::Entity",
        from = "Column::BannerImageMobile",
        to = "super::directus_files::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    DirectusFiles3,
    #[sea_orm(
        belongs_to = "super::directus_files::Entity",
        from = "Column::GridImage",
        to = "super::directus_files::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    DirectusFiles2,
    #[sea_orm(
        belongs_to = "super::directus_files::Entity",
        from = "Column::HeroImage",
        to = "super::directus_files::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    DirectusFiles1,
    #[sea_orm(
        belongs_to = "super::directus_users::Entity",
        from = "Column::UserCreated",
        to = "super::directus_users::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    DirectusUsers2,
    #[sea_orm(
        belongs_to = "super::directus_users::Entity",
        from = "Column::UserUpdated",
        to = "super::directus_users::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    DirectusUsers1,
}

impl ActiveModelBehavior for ActiveModel {}
