//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "directus_shares")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub name: Option<String>,
    pub collection: Option<String>,
    pub item: Option<String>,
    pub role: Option<Uuid>,
    pub password: Option<String>,
    pub user_created: Option<Uuid>,
    pub date_created: Option<DateTimeWithTimeZone>,
    pub date_start: Option<DateTimeWithTimeZone>,
    pub date_end: Option<DateTimeWithTimeZone>,
    pub times_used: Option<i32>,
    pub max_uses: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::directus_collections::Entity",
        from = "Column::Collection",
        to = "super::directus_collections::Column::Collection",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    DirectusCollections,
    #[sea_orm(
        belongs_to = "super::directus_roles::Entity",
        from = "Column::Role",
        to = "super::directus_roles::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    DirectusRoles,
    #[sea_orm(has_many = "super::directus_sessions::Entity")]
    DirectusSessions,
    #[sea_orm(
        belongs_to = "super::directus_users::Entity",
        from = "Column::UserCreated",
        to = "super::directus_users::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    DirectusUsers,
}

impl Related<super::directus_collections::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DirectusCollections.def()
    }
}

impl Related<super::directus_roles::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DirectusRoles.def()
    }
}

impl Related<super::directus_sessions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DirectusSessions.def()
    }
}

impl Related<super::directus_users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DirectusUsers.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
