//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "directus_files")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub storage: String,
    pub filename_disk: Option<String>,
    pub filename_download: String,
    pub title: Option<String>,
    pub r#type: Option<String>,
    pub folder: Option<Uuid>,
    pub uploaded_by: Option<Uuid>,
    pub uploaded_on: DateTimeWithTimeZone,
    pub modified_by: Option<Uuid>,
    pub modified_on: DateTimeWithTimeZone,
    pub charset: Option<String>,
    pub filesize: Option<i64>,
    pub width: Option<i32>,
    pub height: Option<i32>,
    pub duration: Option<i32>,
    pub embed: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub location: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub tags: Option<String>,
    pub metadata: Option<Json>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::directus_folders::Entity",
        from = "Column::Folder",
        to = "super::directus_folders::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    DirectusFolders,
    #[sea_orm(
        belongs_to = "super::directus_users::Entity",
        from = "Column::ModifiedBy",
        to = "super::directus_users::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    DirectusUsers2,
    #[sea_orm(
        belongs_to = "super::directus_users::Entity",
        from = "Column::UploadedBy",
        to = "super::directus_users::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    DirectusUsers1,
    #[sea_orm(has_many = "super::geographical_regions::Entity")]
    GeographicalRegions,
    #[sea_orm(has_many = "super::geographical_regions_files::Entity")]
    GeographicalRegionsFiles,
    #[sea_orm(has_many = "super::hidden_services::Entity")]
    HiddenServices,
    #[sea_orm(has_many = "super::hidden_services_files::Entity")]
    HiddenServicesFiles,
    #[sea_orm(has_many = "super::markets::Entity")]
    Markets,
    #[sea_orm(has_many = "super::markets_files::Entity")]
    MarketsFiles,
    #[sea_orm(has_many = "super::misc::Entity")]
    Misc,
    #[sea_orm(has_many = "super::projects_files::Entity")]
    ProjectsFiles,
    #[sea_orm(has_many = "super::services::Entity")]
    Services,
    #[sea_orm(has_many = "super::services_files::Entity")]
    ServicesFiles,
    #[sea_orm(has_many = "super::studio_locations::Entity")]
    StudioLocations,
    #[sea_orm(has_many = "super::studio_locations_files::Entity")]
    StudioLocationsFiles,
    #[sea_orm(has_many = "super::testimonials::Entity")]
    Testimonials,
}

impl Related<super::directus_folders::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DirectusFolders.def()
    }
}

impl Related<super::geographical_regions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GeographicalRegions.def()
    }
}

impl Related<super::geographical_regions_files::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GeographicalRegionsFiles.def()
    }
}

impl Related<super::hidden_services::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::HiddenServices.def()
    }
}

impl Related<super::hidden_services_files::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::HiddenServicesFiles.def()
    }
}

impl Related<super::markets::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Markets.def()
    }
}

impl Related<super::markets_files::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MarketsFiles.def()
    }
}

impl Related<super::misc::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Misc.def()
    }
}

impl Related<super::projects_files::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProjectsFiles.def()
    }
}

impl Related<super::services::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Services.def()
    }
}

impl Related<super::services_files::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ServicesFiles.def()
    }
}

impl Related<super::studio_locations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StudioLocations.def()
    }
}

impl Related<super::studio_locations_files::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StudioLocationsFiles.def()
    }
}

impl Related<super::testimonials::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Testimonials.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
