//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "directus_notifications")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub timestamp: Option<DateTimeWithTimeZone>,
    pub status: Option<String>,
    pub recipient: Uuid,
    pub sender: Option<Uuid>,
    pub subject: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub message: Option<String>,
    pub collection: Option<String>,
    pub item: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::directus_users::Entity",
        from = "Column::Recipient",
        to = "super::directus_users::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    DirectusUsers2,
    #[sea_orm(
        belongs_to = "super::directus_users::Entity",
        from = "Column::Sender",
        to = "super::directus_users::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    DirectusUsers1,
}

impl ActiveModelBehavior for ActiveModel {}
