//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "geographical_regions")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub sort: Option<i32>,
    pub user_created: Option<Uuid>,
    pub date_created: Option<DateTimeWithTimeZone>,
    pub user_updated: Option<Uuid>,
    pub date_updated: Option<DateTimeWithTimeZone>,
    pub name: Option<String>,
    pub slug: Option<String>,
    pub view_more_name: Option<String>,
    pub search_name: Option<String>,
    pub seo_page_description: Option<String>,
    pub grid_image: Option<Uuid>,
    pub grid_image_description: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub overview: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub project_locations: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub non_linked_services: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub completed_projects_info: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub non_linked_completed_projects: Option<String>,
    pub region_filter: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::directus_files::Entity",
        from = "Column::GridImage",
        to = "super::directus_files::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    DirectusFiles,
    #[sea_orm(
        belongs_to = "super::directus_users::Entity",
        from = "Column::UserCreated",
        to = "super::directus_users::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    DirectusUsers2,
    #[sea_orm(
        belongs_to = "super::directus_users::Entity",
        from = "Column::UserUpdated",
        to = "super::directus_users::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    DirectusUsers1,
    #[sea_orm(has_many = "super::geographical_regions_files::Entity")]
    GeographicalRegionsFiles,
    #[sea_orm(has_many = "super::geographical_regions_news_posts::Entity")]
    GeographicalRegionsNewsPosts,
    #[sea_orm(has_many = "super::geographical_regions_projects::Entity")]
    GeographicalRegionsProjects,
    #[sea_orm(has_many = "super::geographical_regions_services::Entity")]
    GeographicalRegionsServices,
    #[sea_orm(has_many = "super::projects_geographical_regions::Entity")]
    ProjectsGeographicalRegions,
}

impl Related<super::directus_files::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DirectusFiles.def()
    }
}

impl Related<super::geographical_regions_files::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GeographicalRegionsFiles.def()
    }
}

impl Related<super::geographical_regions_news_posts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GeographicalRegionsNewsPosts.def()
    }
}

impl Related<super::geographical_regions_projects::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GeographicalRegionsProjects.def()
    }
}

impl Related<super::geographical_regions_services::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GeographicalRegionsServices.def()
    }
}

impl Related<super::projects_geographical_regions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProjectsGeographicalRegions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
