//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "hidden_services")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub status: String,
    pub sort: Option<i32>,
    pub user_created: Option<Uuid>,
    pub date_created: Option<DateTimeWithTimeZone>,
    pub user_updated: Option<Uuid>,
    pub date_updated: Option<DateTimeWithTimeZone>,
    pub name: Option<String>,
    pub slug: Option<String>,
    pub seo_page_description: Option<String>,
    pub grid_image: Option<Uuid>,
    #[sea_orm(column_type = "Text", nullable)]
    pub overview: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub sub_services: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::directus_files::Entity",
        from = "Column::GridImage",
        to = "super::directus_files::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    DirectusFiles,
    #[sea_orm(
        belongs_to = "super::directus_users::Entity",
        from = "Column::UserCreated",
        to = "super::directus_users::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    DirectusUsers2,
    #[sea_orm(
        belongs_to = "super::directus_users::Entity",
        from = "Column::UserUpdated",
        to = "super::directus_users::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    DirectusUsers1,
    #[sea_orm(has_many = "super::hidden_services_files::Entity")]
    HiddenServicesFiles,
    #[sea_orm(has_many = "super::hidden_services_news_posts::Entity")]
    HiddenServicesNewsPosts,
    #[sea_orm(has_many = "super::hidden_services_team::Entity")]
    HiddenServicesTeam,
    #[sea_orm(has_many = "super::projects_hidden_services::Entity")]
    ProjectsHiddenServices,
}

impl Related<super::directus_files::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DirectusFiles.def()
    }
}

impl Related<super::hidden_services_files::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::HiddenServicesFiles.def()
    }
}

impl Related<super::hidden_services_news_posts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::HiddenServicesNewsPosts.def()
    }
}

impl Related<super::hidden_services_team::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::HiddenServicesTeam.def()
    }
}

impl Related<super::projects_hidden_services::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProjectsHiddenServices.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
