//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "hidden_services_files")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub hidden_services_id: Option<i32>,
    pub directus_files_id: Option<Uuid>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::directus_files::Entity",
        from = "Column::DirectusFilesId",
        to = "super::directus_files::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    DirectusFiles,
    #[sea_orm(
        belongs_to = "super::hidden_services::Entity",
        from = "Column::HiddenServicesId",
        to = "super::hidden_services::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    HiddenServices,
}

impl Related<super::directus_files::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DirectusFiles.def()
    }
}

impl Related<super::hidden_services::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::HiddenServices.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
