//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "hidden_services_news_posts")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub hidden_services_id: Option<i32>,
    pub news_posts_id: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::hidden_services::Entity",
        from = "Column::HiddenServicesId",
        to = "super::hidden_services::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    HiddenServices,
    #[sea_orm(
        belongs_to = "super::news_posts::Entity",
        from = "Column::NewsPostsId",
        to = "super::news_posts::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    NewsPosts,
}

impl Related<super::hidden_services::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::HiddenServices.def()
    }
}

impl Related<super::news_posts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::NewsPosts.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
