//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "markets_news_posts")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub markets_id: Option<i32>,
    pub news_posts_id: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::markets::Entity",
        from = "Column::MarketsId",
        to = "super::markets::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Markets,
    #[sea_orm(
        belongs_to = "super::news_posts::Entity",
        from = "Column::NewsPostsId",
        to = "super::news_posts::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    NewsPosts,
}

impl Related<super::markets::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Markets.def()
    }
}

impl Related<super::news_posts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::NewsPosts.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
