//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "markets")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub status: String,
    pub sort: Option<i32>,
    pub user_created: Option<Uuid>,
    pub date_created: Option<DateTimeWithTimeZone>,
    pub user_updated: Option<Uuid>,
    pub date_updated: Option<DateTimeWithTimeZone>,
    pub name: Option<String>,
    pub slug: Option<String>,
    pub seo_page_description: Option<String>,
    pub medium_name: Option<String>,
    pub short_name: Option<String>,
    pub view_more_name: Option<String>,
    pub filter_button_name: Option<String>,
    pub sort_priority: Option<i32>,
    pub grid_image: Option<Uuid>,
    pub grid_image_description: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub overview: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub sub_services: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub team_leaders_text: Option<String>,
    pub default_sort: Option<bool>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::directus_files::Entity",
        from = "Column::GridImage",
        to = "super::directus_files::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    DirectusFiles,
    #[sea_orm(
        belongs_to = "super::directus_users::Entity",
        from = "Column::UserCreated",
        to = "super::directus_users::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    DirectusUsers2,
    #[sea_orm(
        belongs_to = "super::directus_users::Entity",
        from = "Column::UserUpdated",
        to = "super::directus_users::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    DirectusUsers1,
    #[sea_orm(has_many = "super::markets_files::Entity")]
    MarketsFiles,
    #[sea_orm(has_many = "super::markets_news_posts::Entity")]
    MarketsNewsPosts,
    #[sea_orm(has_many = "super::markets_projects::Entity")]
    MarketsProjects,
    #[sea_orm(has_many = "super::markets_team::Entity")]
    MarketsTeam,
    #[sea_orm(has_many = "super::projects_markets::Entity")]
    ProjectsMarkets,
}

impl Related<super::directus_files::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DirectusFiles.def()
    }
}

impl Related<super::markets_files::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MarketsFiles.def()
    }
}

impl Related<super::markets_news_posts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MarketsNewsPosts.def()
    }
}

impl Related<super::markets_projects::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MarketsProjects.def()
    }
}

impl Related<super::markets_team::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MarketsTeam.def()
    }
}

impl Related<super::projects_markets::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProjectsMarkets.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
