//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "news_topics")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub status: String,
    pub sort: Option<i32>,
    pub user_created: Option<Uuid>,
    pub date_created: Option<DateTimeWithTimeZone>,
    pub user_updated: Option<Uuid>,
    pub date_updated: Option<DateTimeWithTimeZone>,
    pub name: Option<String>,
    #[sea_orm(unique)]
    pub slug: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::directus_users::Entity",
        from = "Column::UserCreated",
        to = "super::directus_users::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    DirectusUsers2,
    #[sea_orm(
        belongs_to = "super::directus_users::Entity",
        from = "Column::UserUpdated",
        to = "super::directus_users::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    DirectusUsers1,
    #[sea_orm(has_many = "super::news_posts_news_topics::Entity")]
    NewsPostsNewsTopics,
}

impl Related<super::news_posts_news_topics::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::NewsPostsNewsTopics.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
