//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "news_posts_news_topics")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub news_posts_id: Option<i32>,
    pub news_topics_id: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::news_posts::Entity",
        from = "Column::NewsPostsId",
        to = "super::news_posts::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    NewsPosts,
    #[sea_orm(
        belongs_to = "super::news_topics::Entity",
        from = "Column::NewsTopicsId",
        to = "super::news_topics::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    NewsTopics,
}

impl Related<super::news_posts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::NewsPosts.def()
    }
}

impl Related<super::news_topics::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::NewsTopics.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
