//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "news_posts")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub status: String,
    pub sort: Option<i32>,
    pub user_created: Option<Uuid>,
    pub date_created: Option<DateTimeWithTimeZone>,
    pub user_updated: Option<Uuid>,
    pub date_updated: Option<DateTimeWithTimeZone>,
    pub post_title: Option<String>,
    #[sea_orm(unique)]
    pub slug: Option<String>,
    pub published_date: Option<DateTime>,
    pub seo_page_description: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub article_preview: Option<String>,
    pub grid_image: Option<Uuid>,
    pub grid_image_description: Option<String>,
    pub topics_list: Option<String>,
    pub hero_image: Option<Uuid>,
    pub hero_image_description: Option<String>,
    pub hero_image_crop_attachment: Option<String>,
    pub hero_video: Option<String>,
    pub featured: Option<bool>,
    #[sea_orm(column_type = "Text", nullable)]
    pub post_body: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::directus_files::Entity",
        from = "Column::GridImage",
        to = "super::directus_files::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    DirectusFiles2,
    #[sea_orm(
        belongs_to = "super::directus_files::Entity",
        from = "Column::HeroImage",
        to = "super::directus_files::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    DirectusFiles1,
    #[sea_orm(
        belongs_to = "super::directus_users::Entity",
        from = "Column::UserCreated",
        to = "super::directus_users::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    DirectusUsers2,
    #[sea_orm(
        belongs_to = "super::directus_users::Entity",
        from = "Column::UserUpdated",
        to = "super::directus_users::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    DirectusUsers1,
    #[sea_orm(has_many = "super::geographical_regions_news_posts::Entity")]
    GeographicalRegionsNewsPosts,
    #[sea_orm(has_many = "super::hidden_services_news_posts::Entity")]
    HiddenServicesNewsPosts,
    #[sea_orm(has_many = "super::markets_news_posts::Entity")]
    MarketsNewsPosts,
    #[sea_orm(has_many = "super::news_posts_news_topics::Entity")]
    NewsPostsNewsTopics,
    #[sea_orm(has_many = "super::news_posts_team::Entity")]
    NewsPostsTeam,
    #[sea_orm(has_many = "super::services_news_posts::Entity")]
    ServicesNewsPosts,
    #[sea_orm(has_many = "super::studio_locations_news_posts::Entity")]
    StudioLocationsNewsPosts,
}

impl Related<super::geographical_regions_news_posts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GeographicalRegionsNewsPosts.def()
    }
}

impl Related<super::hidden_services_news_posts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::HiddenServicesNewsPosts.def()
    }
}

impl Related<super::markets_news_posts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MarketsNewsPosts.def()
    }
}

impl Related<super::news_posts_news_topics::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::NewsPostsNewsTopics.def()
    }
}

impl Related<super::news_posts_team::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::NewsPostsTeam.def()
    }
}

impl Related<super::services_news_posts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ServicesNewsPosts.def()
    }
}

impl Related<super::studio_locations_news_posts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StudioLocationsNewsPosts.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
