//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "projects_geographical_regions")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub projects_id: Option<i32>,
    pub geographical_regions_id: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::geographical_regions::Entity",
        from = "Column::GeographicalRegionsId",
        to = "super::geographical_regions::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    GeographicalRegions,
    #[sea_orm(
        belongs_to = "super::projects::Entity",
        from = "Column::ProjectsId",
        to = "super::projects::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Projects,
}

impl Related<super::geographical_regions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GeographicalRegions.def()
    }
}

impl Related<super::projects::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Projects.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
