//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "projects")]
pub struct Model {
    #[sea_orm(primary_key)]
    #[serde(skip_deserializing)]
    pub id: i32,
    pub sort: Option<i32>,
    pub user_created: Option<Uuid>,
    #[serde(alias = "Created On")]
    pub date_created: Option<DateTimeWithTimeZone>,
    pub user_updated: Option<Uuid>,
    #[serde(alias = "Updated On")]
    pub date_updated: Option<DateTimeWithTimeZone>,
    #[serde(alias = "Project Title")]
    pub project_title: Option<String>,
    #[serde(alias = "Slug")]
    pub slug: Option<String>,
    #[serde(alias = "Project Title (Short)")]
    pub project_title_short: Option<String>,
    #[serde(alias = "SEO Page Description")]
    pub seo_page_description: Option<String>,
    #[serde(alias = "Home Page Slider")]
    pub home_page_slider: Option<bool>,
    #[serde(alias = "Grid Image")]
    pub grid_image: Option<Uuid>,
    #[serde(alias = "Grid Image Description")]
    pub grid_image_description: Option<String>,
    #[serde(alias = "Hero Image")]
    pub hero_image: Option<Uuid>,
    #[serde(alias = "Hero Image Description")]
    pub hero_image_description: Option<String>,
    #[serde(alias = "Hero Image Crop Attachment")]
    pub hero_image_crop_attachment: Option<String>,
    #[serde(alias = "Hero Video ID")]
    pub hero_video_id: Option<String>,
    #[serde(alias = "Location")]
    pub location: Option<String>,
    #[serde(alias = "Regions and Studio Locations List")]
    pub regions_and_studio_locations_list: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    #[serde(alias = "Project Description")]
    pub project_description: Option<String>,
    #[serde(alias = "Project Opening Date")]
    pub project_opening_date: Option<DateTime>,
    #[sea_orm(column_type = "Text", nullable)]
    pub non_linked_markets: Option<String>,
    pub markets_list: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub non_linked_services: Option<String>,
    pub services_list: Option<String>,
    pub misc_filters_list: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub client: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub design_awards: Option<String>,
    pub collaborators: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub project_body: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::awards::Entity")]
    Awards,
    #[sea_orm(
        belongs_to = "super::directus_files::Entity",
        from = "Column::GridImage",
        to = "super::directus_files::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    DirectusFiles2,
    #[sea_orm(
        belongs_to = "super::directus_files::Entity",
        from = "Column::HeroImage",
        to = "super::directus_files::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    DirectusFiles1,
    #[sea_orm(
        belongs_to = "super::directus_users::Entity",
        from = "Column::UserCreated",
        to = "super::directus_users::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    DirectusUsers2,
    #[sea_orm(
        belongs_to = "super::directus_users::Entity",
        from = "Column::UserUpdated",
        to = "super::directus_users::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    DirectusUsers1,
    #[sea_orm(has_many = "super::geographical_regions_projects::Entity")]
    GeographicalRegionsProjects,
    #[sea_orm(has_many = "super::markets_projects::Entity")]
    MarketsProjects,
    #[sea_orm(has_many = "super::misc_projects::Entity")]
    MiscProjects,
    #[sea_orm(has_many = "super::projects_files::Entity")]
    ProjectsFiles,
    #[sea_orm(has_many = "super::projects_geographical_regions::Entity")]
    ProjectsGeographicalRegions,
    #[sea_orm(has_many = "super::projects_hidden_markets::Entity")]
    ProjectsHiddenMarkets,
    #[sea_orm(has_many = "super::projects_hidden_services::Entity")]
    ProjectsHiddenServices,
    #[sea_orm(has_many = "super::projects_markets::Entity")]
    ProjectsMarkets,
    #[sea_orm(has_many = "super::projects_services::Entity")]
    ProjectsServices,
    #[sea_orm(has_many = "super::projects_studio_locations::Entity")]
    ProjectsStudioLocations,
    #[sea_orm(has_many = "super::services_projects::Entity")]
    ServicesProjects,
    #[sea_orm(has_many = "super::studio_locations_projects::Entity")]
    StudioLocationsProjects,
    #[sea_orm(has_many = "super::team_projects::Entity")]
    TeamProjects,
    #[sea_orm(has_many = "super::testimonials::Entity")]
    Testimonials,
}

impl Related<super::awards::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Awards.def()
    }
}

impl Related<super::geographical_regions_projects::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GeographicalRegionsProjects.def()
    }
}

impl Related<super::markets_projects::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MarketsProjects.def()
    }
}

impl Related<super::misc_projects::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MiscProjects.def()
    }
}

impl Related<super::projects_files::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProjectsFiles.def()
    }
}

impl Related<super::projects_geographical_regions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProjectsGeographicalRegions.def()
    }
}

impl Related<super::projects_hidden_markets::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProjectsHiddenMarkets.def()
    }
}

impl Related<super::projects_hidden_services::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProjectsHiddenServices.def()
    }
}

impl Related<super::projects_markets::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProjectsMarkets.def()
    }
}

impl Related<super::projects_services::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProjectsServices.def()
    }
}

impl Related<super::projects_studio_locations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProjectsStudioLocations.def()
    }
}

impl Related<super::services_projects::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ServicesProjects.def()
    }
}

impl Related<super::studio_locations_projects::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StudioLocationsProjects.def()
    }
}

impl Related<super::team_projects::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TeamProjects.def()
    }
}

impl Related<super::testimonials::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Testimonials.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
