//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "studio_locations")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub status: String,
    pub sort: Option<i32>,
    pub user_created: Option<Uuid>,
    pub date_created: Option<DateTimeWithTimeZone>,
    pub user_updated: Option<Uuid>,
    pub date_updated: Option<DateTimeWithTimeZone>,
    pub location: Option<String>,
    pub slug: Option<String>,
    pub view_more_name: Option<String>,
    pub search_name: Option<String>,
    pub seo_page_description: Option<String>,
    pub grid_image: Option<Uuid>,
    pub location_abbreviated: Option<String>,
    pub location_full: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub overview: Option<String>,
    pub office_director: Option<i32>,
    #[sea_orm(column_type = "Text", nullable)]
    pub address: Option<String>,
    pub contact_phone: Option<String>,
    pub contact_email: Option<String>,
    pub sort_priority: Option<i32>,
    pub studio_filter: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub hubspot_tracking_email: Option<String>,
    pub noindex: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::directus_files::Entity",
        from = "Column::GridImage",
        to = "super::directus_files::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    DirectusFiles,
    #[sea_orm(
        belongs_to = "super::directus_users::Entity",
        from = "Column::UserCreated",
        to = "super::directus_users::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    DirectusUsers2,
    #[sea_orm(
        belongs_to = "super::directus_users::Entity",
        from = "Column::UserUpdated",
        to = "super::directus_users::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    DirectusUsers1,
    #[sea_orm(has_many = "super::projects_studio_locations::Entity")]
    ProjectsStudioLocations,
    #[sea_orm(has_many = "super::studio_locations_files::Entity")]
    StudioLocationsFiles,
    #[sea_orm(has_many = "super::studio_locations_news_posts::Entity")]
    StudioLocationsNewsPosts,
    #[sea_orm(has_many = "super::studio_locations_projects::Entity")]
    StudioLocationsProjects,
    #[sea_orm(
        belongs_to = "super::team::Entity",
        from = "Column::OfficeDirector",
        to = "super::team::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Team,
}

impl Related<super::directus_files::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DirectusFiles.def()
    }
}

impl Related<super::projects_studio_locations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProjectsStudioLocations.def()
    }
}

impl Related<super::studio_locations_files::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StudioLocationsFiles.def()
    }
}

impl Related<super::studio_locations_news_posts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StudioLocationsNewsPosts.def()
    }
}

impl Related<super::studio_locations_projects::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StudioLocationsProjects.def()
    }
}

impl Related<super::team::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Team.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
