//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "team")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub status: String,
    pub sort: Option<i32>,
    pub user_created: Option<Uuid>,
    pub date_created: Option<DateTimeWithTimeZone>,
    pub user_updated: Option<Uuid>,
    pub date_updated: Option<DateTimeWithTimeZone>,
    pub name: Option<String>,
    #[sea_orm(unique)]
    pub slug: Option<String>,
    pub seo_page_description: Option<String>,
    pub full_title: Option<String>,
    pub short_title: Option<String>,
    pub headshot: Option<Uuid>,
    pub headshot_description: Option<String>,
    pub featured_image: Option<Uuid>,
    pub featured_image_description: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub bio: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub education: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub honors: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub speaking_publications_abstract_topics: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub expertise: Option<String>,
    pub contact_phone_1: Option<String>,
    pub contact_phone_1_extension: Option<i32>,
    pub contact_phone_2: Option<String>,
    pub contact_phone_2_extension: Option<String>,
    pub contact_email: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub hubspot_tracking_email: Option<String>,
    pub instagram_url: Option<String>,
    pub linkedin_url: Option<String>,
    pub noindex: Option<String>,
    pub sort_priority: Option<i32>,
    pub title_ranking: Option<i32>,
    pub banner_grid_image_bw: Option<Uuid>,
    pub banner_grid_image_color: Option<Uuid>,
    pub banner_grid_image_description: Option<String>,
    pub banner_grid_image_sort: Option<i32>,
    pub display_latest_articles: Option<bool>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::directus_files::Entity",
        from = "Column::BannerGridImageBw",
        to = "super::directus_files::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    DirectusFiles4,
    #[sea_orm(
        belongs_to = "super::directus_files::Entity",
        from = "Column::BannerGridImageColor",
        to = "super::directus_files::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    DirectusFiles3,
    #[sea_orm(
        belongs_to = "super::directus_files::Entity",
        from = "Column::FeaturedImage",
        to = "super::directus_files::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    DirectusFiles2,
    #[sea_orm(
        belongs_to = "super::directus_files::Entity",
        from = "Column::Headshot",
        to = "super::directus_files::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    DirectusFiles1,
    #[sea_orm(
        belongs_to = "super::directus_users::Entity",
        from = "Column::UserCreated",
        to = "super::directus_users::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    DirectusUsers2,
    #[sea_orm(
        belongs_to = "super::directus_users::Entity",
        from = "Column::UserUpdated",
        to = "super::directus_users::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    DirectusUsers1,
    #[sea_orm(has_many = "super::hidden_services_team::Entity")]
    HiddenServicesTeam,
    #[sea_orm(has_many = "super::markets_team::Entity")]
    MarketsTeam,
    #[sea_orm(has_many = "super::misc_team::Entity")]
    MiscTeam,
    #[sea_orm(has_many = "super::news_posts_team::Entity")]
    NewsPostsTeam,
    #[sea_orm(has_many = "super::services_team::Entity")]
    ServicesTeam,
    #[sea_orm(has_many = "super::studio_locations::Entity")]
    StudioLocations,
    #[sea_orm(has_many = "super::team_projects::Entity")]
    TeamProjects,
}

impl Related<super::hidden_services_team::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::HiddenServicesTeam.def()
    }
}

impl Related<super::markets_team::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MarketsTeam.def()
    }
}

impl Related<super::misc_team::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MiscTeam.def()
    }
}

impl Related<super::news_posts_team::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::NewsPostsTeam.def()
    }
}

impl Related<super::services_team::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ServicesTeam.def()
    }
}

impl Related<super::studio_locations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StudioLocations.def()
    }
}

impl Related<super::team_projects::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TeamProjects.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
