//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "testimonials")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub status: String,
    pub sort: Option<i32>,
    pub user_created: Option<Uuid>,
    pub date_created: Option<DateTimeWithTimeZone>,
    pub user_updated: Option<Uuid>,
    pub date_updated: Option<DateTimeWithTimeZone>,
    pub quote_attribution: Option<String>,
    pub slug: Option<String>,
    pub quote_attribution_job_title: Option<String>,
    pub company_name: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub quote: Option<String>,
    pub banner_image: Option<Uuid>,
    pub banner_image_description: Option<String>,
    pub associated_project: Option<i32>,
    pub sort_priority: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::directus_files::Entity",
        from = "Column::BannerImage",
        to = "super::directus_files::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    DirectusFiles,
    #[sea_orm(
        belongs_to = "super::directus_users::Entity",
        from = "Column::UserCreated",
        to = "super::directus_users::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    DirectusUsers2,
    #[sea_orm(
        belongs_to = "super::directus_users::Entity",
        from = "Column::UserUpdated",
        to = "super::directus_users::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    DirectusUsers1,
    #[sea_orm(
        belongs_to = "super::projects::Entity",
        from = "Column::AssociatedProject",
        to = "super::projects::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Projects,
}

impl Related<super::directus_files::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DirectusFiles.def()
    }
}

impl Related<super::projects::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Projects.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
