//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "test")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub status: String,
    pub sort: Option<i32>,
    pub user_created: Option<Uuid>,
    pub date_created: Option<DateTimeWithTimeZone>,
    pub user_updated: Option<Uuid>,
    pub date_updated: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::directus_users::Entity",
        from = "Column::UserCreated",
        to = "super::directus_users::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    DirectusUsers2,
    #[sea_orm(
        belongs_to = "super::directus_users::Entity",
        from = "Column::UserUpdated",
        to = "super::directus_users::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    DirectusUsers1,
}

impl ActiveModelBehavior for ActiveModel {}
