import { redirect, type Handle } from '@sveltejs/kit';

const redirects: any = {
	'/about-rsm/': '/about',
	'/about-rsm': '/about',
	'/work/project-types/city-signage/': '/markets/civic-design',
	'/work/project-types/city-signage': '/markets/civic-design',
	'/service/architectural-graphic-design': '/services/environmental-graphic-design',
	'/service/experiential-design': '/services/environmental-graphic-design',
	'/work/services/': '/expertise',
	'/work/project-types/residential-community-design/': '/markets/residential-community',
	'/work/services/placemaking-public-art/': '/services/placemaking',
	'/work/project-types/city-signage-design/': '/markets/civic-design',
	'/rsm/donor-recognition': '/services/donor-recognition',
	'/blog/': '/news',
	'/conversation/': '/contact',
	'/conversation': '/contact',
	'/rsm-design-principals': '/about',
	'/our-story': '/about',
	'/work/project-types/park-design/': '/markets/park-design',
	'/community/': '/',
	'/community': '/',
	'/news/what-is-wayfinding-part-1-its-all-about-human-needs': '/news/what-is-wayfinding',
	'/news/what-is-wayfinding-part-2-the-city-as-a-model': '/news/what-is-wayfinding',
	'/news/what-is-wayfinding-part-3-wayfinding-is-more-than-just-signage': '/news/what-is-wayfinding',
	'/miami-waterfront-miwaterfront/': '/work/miami-baywalk',
	'/what-is-environmental-graphic-design-part-1-the-name-is-confusing/' : '/news/what-is-environmental-graphic-design-part-1-the-name-is-confusing',
	'/work/services/wayfinding-design/': '/services/wayfinding-signage',
	'/work/services/environmental-graphic-design/': '/services/environmental-graphic-design',
	'/news/what-is-wayfinding-part-4-whats-next-in-wayfinding': '/news/what-is-digital-wayfinding',
	'/work/omni-pga-frisco-resort-branding': '/work/omni-pga-frisco-resort',
	'/blog/what-is-wayfinding-4-part-series/': '/news/what-is-digital-wayfinding',
	'/creating-social-media-places/': '/news/creating-social-media-places',
	'/cultural-districts/': '/news/cultural-districts',
	'/markets/services/branding-logo-design': '/services/branding-logo-design',
	'/markets/services/master-sign-programs': '/services/master-sign-programs',
	'/markets/team/harry-mark-faia': '/team/harry-mark-faia',
	'/rsm/digital-integration': '/services/digital-integration',
	'/rsm/exhibit-design': '/services/exhibit-design',
	'/services/placemaking-design': '/services/placemaking',
	'/using-public-art-to-add-value-to-projects/': '/news/using-public-art-to-add-value-to-projects',
	'/using-public-art-to-add-value-to-projects': '/news/using-public-art-to-add-value-to-projects',
	'/wayfinding-design/': '/services/wayfinding-signage',
	'/what-is-environmental-graphic-design-part-2-egd-is-about-emotional-connections/': '/news/what-is-environmental-graphic-design-part-2-egd-is-about-emotional-connections',
	'/work/aerocity-new-delihi-india/': '/work/aerocity',
	'/work/aerocity-new-delihi-india': '/work/aerocity',
	'/work/architecture-and-design-exchange-dallas-tx/': '/work/ad-ex-dallas-tx',
	'/work/architecture-and-design-exchange-dallas-tx': '/work/ad-ex-dallas-tx',
	'/work/fifth-broadway-nashville-tennessee/': '/work/fifth-and-broadway',
	'/work/fifth-broadway-nashville-tennessee': '/work/fifth-and-broadway',
	'/work/oxigeno-human-playground-san-jose-costa-rica/': '/work/oxigeno-human-playground',
	'/work/oxigeno-human-playground-san-jose-costa-rica': '/work/oxigeno-human-playground',
	'/work/project-types/higher-education-design/': '/markets/education-design',
	'/work/services/architectural-graphic-design/': '/services/architectural-graphic-design',
	'/work/services/branding-logo-design/': '/services/branding-logo-design',
	'/work/services/experiential-design/': '/services/experiential-graphic-design',
	'/work/services/master-signage-programs/': '/services/master-sign-programs',
	'/work/summit-bechtel-reserve-2': '/work/the-summit-bechtel-reserve',
	'/work/summit-bechtel-reserve-2/': '/work/the-summit-bechtel-reserve',
	'/work/The-Crescent-Hotel': '/work/crescent-hotel',
	'/work/hospitality-information?s=1': '/work/hospitality-information',
	'/work/pacific-city-case-study/': '/work/pacific-city-case-study',
	'/work/san-ysidro-port-of-entry-san-diego-ca?r=1': '/work/san-ysidro-port-of-entry-san-diego-ca',
	'/work/mesa-court-towers-irvine-ca/': '/work/mesa-court-towers-irvine-ca',
	'/work/biovista-san-diego?s=1': '/work/biovista-san-diego',
	'/work/pavilion-park-irvine-ca/': '/work/pavilion-park-irvine-ca',
};

export const handle: Handle = async ({ event, resolve }) => {
	if (redirects[event.url.pathname]) throw redirect(301, redirects[event.url.pathname]);
	return await resolve(event);
};